### PR TITLE
Renamed no_gimme env var to skip_go_installation

### PR DESCRIPTION
**Pull request by algojack**
## Summary

Renamed no_gimme env var to skip_go_installation

## Test Plan

Checking travis and circleci tests below

### CODE REVIEW

**Review by tsachiherman — COMMENTED** [review]
looks good to me.. is there any particular reason that pushed you toward this change ?
( just curious, since I can't see any obvious reason )

**Comment by winder** [comment]
This is a follow-up item from the circleci work. The variable was added due to a windows issue, I think the new name is more self-documenting.

**Review by winder — APPROVED** [review]
LGTM

**Review by algobarb — APPROVED** [review]
I wondered about the notes you added to the parent issue, but the changes here look good.

**Pull request merged**
