### PR TITLE
[WIP] Algod: delete old partkey database file after importing its data to the node's ParticipationRegistry

### PR DESCRIPTION
**Pull request by Aharonee**
Fix a minor issue where old participation DB files are not deleted after being successfully imported into the registry.

This causes the node to try re-loading the file every time it is started.

### CODE REVIEW

**Comment by cce** [comment]
A few releases ago, I was worried that if we made a change to add a new case where we call os.Remove() on part keys, it might surprise users still using the legacy method of adding part keys to algod, who could be concerned that their keys had disappeared, or had not adapted their deployment automation to account for keys disappearing. This is similar to the logic of the `delete-input` flag that you're required to provide to use to positively confirm you're OK with the part key file being deleted.

But if enough time has passed since the last time we released changes to goal and the REST API surrounding part keys, and we think it will not surprise node operators, maybe this is no longer a big concern.. curious your thoughts @barnjamin @winder?

Another option would be to just ignore keys dropped in the directory, and stop scanning the directory for keys to import, and instead require using REST API / goal. Then the user would be forced would be presented with a clear warning and have to explicitly confirm they are OK with the part key being deleted via the `delete-input` flag

**Comment by winder** [comment]
goal doesn't use the REST API yet, not until the release which is going out soon.

**Comment by cce** [comment]
Well, I still worry that since we currently only delete your part keys when you explicitly provide `--delete-input` to goal, it may be a big surprise to some to have your part key files deleted just by running algod.

**Review by winder — CHANGES_REQUESTED** [review]
Declining per comments.

**Comment by algorandskiy** [comment]
a year without activity

**Pull request closed without merging**
