### PR TITLE
Fix flaky test in randomized ABI encoding test

### PR DESCRIPTION
**Pull request by ahangsu**
## Summary

Previously @cce noticed that there's a flaky test in ABI encoding.

> Chris Erway: just encountered a PR of mine failing due to what looks like a new flaky test related to encoding randomly generated values? https://app.circleci.com/pipelines/github/algorand/go-algorand/3937/workflows/7bd0914e-57f8-4d7e-9fa9-026f74c831bf/jobs/58162
> 

The reason for the flaky test is that we randomly generate variables to test ABI encoding, and it turns out that the generated ABI-encoding bytes is larger than `uint16` limit. The encoder would just throw an error complaining `encode length exceeds uint16 maximum`.

The solution is to scale down the parameters for generating random variables, to decrease the generated bytes length, not to reach the `2^16` length limit.

We gathered the constants in test scripts for better readability.

## Test Plan

We should expect that the modification eliminate the flaky test chance...

### CODE REVIEW

**Review by jannotti — COMMENTED** [review]
This seems like the right fix.  Could you also put in come notes about how you came up with appropriate constants? For example, if you use something that is B bytes lony X times in a loop that runs Y times, perhaps you need B*X*Y to be less that 1<<16.

In fact, you could put a couple simple require.Less() calls in on the constants to document the requirements.

**Comment by tzaffi** [comment]
For future reference, putting a link the the @cce's [original slack message](https://algorand-internal.slack.com/archives/C020LLY8VBM/p1640112787497300).

**Review by tzaffi — COMMENTED** [review]
Just one suggestions.

**Review by tzaffi — DISMISSED** [review]
LGTM

**Comment by jannotti** [comment]
> ```go
> require.NoError(t, err, "failure to encode value", fmt.Sprintf("failing test object:\n%#v\n", testObj))
> ```

Using Go's require, you can omit the fmt.Sprintf, and just use
```
require.NoError(t, err, "failure to encode %#v", testObj)
```

**Review by jannotti — APPROVED** [review]

**Pull request merged**
