### PR TITLE
Remove `check_clean_enlistment.sh` script

### PR DESCRIPTION
**Pull request by btoll**
Note that I changed this because I ran into this again with the build pipeline work.  I've found the word "enlistment" to be confusing, so I wanted to change that message.

----------------------------

This file was only being referenced from one file, so I removed the
conditional that was in it to where it was being referenced.

- Improved warning message when the workspace is dirty.
- Fixed bug where files like `buildnumber.datdat` are not flagged.
- Fixed warnings discovered by shellcheck.

### CODE REVIEW

**Comment by algobolson** [comment]
There are a lot of error checks. Might be simpler to run bash with `set -e` and just require every command to pass?

**Comment by btoll** [comment]
Yes, good idea, I'll change that.

**Comment by btoll** [comment]
Ok, will change.

**Comment by btoll** [comment]
That was an oversight.  Thanks for catching that.

**Pull request merged**
