### PR TITLE
documentation: remove tlhc and tutorial from logic package

### PR DESCRIPTION
**Pull request by barnjamin**
These seem vestigial, if needed we can move them to docs somewhere

### CODE REVIEW

**Review by jannotti — DISMISSED** [review]
I don't know of any need for them.

**Review by ahangsu — DISMISSED** [review]

**Comment by ahangsu** [comment]
I guess if you want to satisfy the CI, you might want to remove the `e2e-teal.sh` in `e2e-subs`...

**Comment by barnjamin** [comment]
@ahangsu good point, I failed to realize there were tests for it. I've moved the python script to the e2e subs directory instead of deleting it completely and updated the path on the test script

**Review by ahangsu — APPROVED** [review]
lgtm

**Comment by jannotti** [comment]
I sort of understood why we might want to remove code (`tlhc.py`), because we have to keep it working in the face of changes. But now we are keeping the code, and only removing documentation. Why do that? The tutorial feels a bit outdated, but not incorrect. It's outdated because apps are powerful enough now that logicsigs are a less common choice. But what harm is done by having some explanatory text in the repo? Is the problem that the tutroial auto-appears in some user facing website? If so, we could change that instead.

**Comment by barnjamin** [comment]
Keeping the code because I didn't want to remove a test. Initially thought it was outdated enough and seemed awkward to have as the only example here. 

I'll close this out though since we're not actually gaining anything by just moving the code

**Pull request closed without merging**
