### PR TITLE
CICD: update build pipeline for darwin-amd64

### PR DESCRIPTION
**Pull request by algolucky**
## Summary

- updates the build pipeline to incorporate darwin `amd64` builds into the internal build pipeline

### CODE REVIEW

**Review by algojohnlee — APPROVED** [review]

**Comment by algojohnlee** [comment]
Presuming we have the amd64 mac agent set up, I think this is good.

**Review by onetechnical — APPROVED** [review]

**Review by onetechnical — APPROVED** [review]

**Review by algobarb — APPROVED** [review]
This looks good to me. I wonder when we can try removing the stash.

**Comment by algolucky** [comment]
@algobard I can add that in, and run a quick test.

**Comment by algobarb** [comment]
> > I wonder when we can try removing the stash.
> 
> @algobarb I can add that in, and run a quick test. Or just have a quick follow up.

No don't worry about it. Could be a separate ticket to make sure nothing external depends on it.

**Review by egieseke — APPROVED** [review]

**Pull request merged**
