### PR TITLE
CICD: create model mainnet (mmnet) recipe based on scenario2

### PR DESCRIPTION
**Pull request by algolucky**
## Summary

- this creates a new recipe based off of `scenario2` that models mainnet (mmnet) with 136 relays across multiple regions (204 total)
- updates `hosttemplates.json` to include regions that haven't been used before
- fixed a typo where `AWS-AP-SOUTH-1--m5d.2xl` should be `AWS-AP-SOUTH-1-m5d.2xl`

## Test Plan

- see performance pipeline runs for this scenario

## notes

- I called it `mmnet` in an effort to be as short as possible, but still make sense. this value tends to be used for DNS records and those tend to have size limits.

### CODE REVIEW

**Review by egieseke — CHANGES_REQUESTED** [review]
We should create a separate mainnet recipe for this so that we don't affect our baseline for scenario2 testing.

**Comment by brianolson** [comment]
my recent testing shows that m5d.2xl (8 cores) is enough for regular participating nodes up to at least 5 wallets each, so we could save a bit of money on those, otherwise looks good. (I've been running with m5d.4xl for relays and NPN)

**Comment by algolucky** [comment]
@brianolson this was based on `scenario2`, the only difference is the number of relays and the regional distribution. Your experience here is greater than mine, so instance type and # of algod nodes would be something I'd hope you'd keep me straight about.

**Comment by algobarb** [comment]
> my recent testing shows that m5d.2xl (8 cores) is enough for regular participating nodes up to at least 5 wallets each, so we could save a bit of money on those, otherwise looks good. (I've been running with m5d.4xl for relays and NPN) BUT, I'm only running one `algod` per m5d.2xl, this net.json is loading up 4 or 5 algod on each ec2 instance?

When I took a look at the net.json, I think this recipe is running:
- 1 relay per host. 136 hosts.
- 5 participating nodes per host: 10 wallets, 2 per participating node. 40 Hosts total
- 2 NPN node per host: 1 wallet. 15 Hosts total

I think they correlate with the numbers in the Makefile here: https://github.com/algolucky/go-algorand/blob/cicd/scenario2-mainnet-relay-model/test/testdata/deployednettemplates/recipes/mmnet/Makefile (200 / 40 = 5 nodes in each N host)

**Review by algojack — APPROVED** [review]

**Review by cce — APPROVED** [review]
This is great, capturing the relay topology will be really helpful in modeling the network. For the next iteration I hope to look at getting a distribution of participating and non-participating nodes that roughly match mainnet too.

**Review by egieseke — APPROVED** [review]

**Pull request merged**
