### PR TITLE
Extend catchpoint wait for round timeout from 10 to 60 seconds.

### PR DESCRIPTION
**Pull request by egieseke**
## Summary

Extend catchpoint test next round timeout from 10 to 60 seconds to avoid test failure.

## Test Plan

Tested locally.

### CODE REVIEW

**Review by bricerisingalgorand — APPROVED** [review]
This looks reasonable to me

**Comment by tsachiherman** [comment]
while it's reasonable change, I would be happy to hear why this issue start failing - 
is advancing a single round takes 60 seconds ? if so, maybe we need to stop everything and fix that bug ?

**Comment by egieseke** [comment]
> while it's reasonable change, I would be happy to hear why this issue start failing -
> is advancing a single round takes 60 seconds ? if so, maybe we need to stop everything and fix that bug ?

It now takes more than 10 seconds and it would be good to know why.  I will create a ticket a separate ticket to investigate.

**Comment by algobarb** [comment]
Since this is to fix the nightly builds, I think it seems ok to go ahead with this as we troubleshoot why it's taking more than 10 seconds and whether 60 seconds is good.

**Review by algobarb — APPROVED** [review]

**Comment by onetechnical** [comment]
I'm okay with trying this to see if it unblocks the nightly builds, but I want to know _how_ long it's taking and why, as to Tsachi's point, if it really is taking > 10s to advance a round, that would be very bad. (I don't think this is actually the case, there may be something else in the testing apparatus causing a problem.)

**Pull request merged**
