### PR TITLE
docs: increase heading levels, thus only one h1 is used

### PR DESCRIPTION
**Pull request by abebeos**
(1st part of invalidly closed #5280)

trivial

### CODE REVIEW

**Review by jannotti — APPROVED** [review]
Given the world-wide shortage of `h1`s, and the supply-chain issues that are likely to keep `h1` levels at an all-time low, this seems like an important change to cut our overall `h1` budget.

**Comment by abebeos** [comment]
besides above mentioned shortage/supply-chain problems:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page

(& other articles)

**Review by algorandskiy — DISMISSED** [review]
This change does not have value. The [CommonMark Spec](https://spec.commonmark.org/0.30) does not call `# thing` a title.

**Comment by abebeos** [comment]
> The [CommonMark Spec](https://spec.commonmark.org/0.30) does not call `# thing` a title.

Maybe try this one:

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

Works very well on github.

**Comment by abebeos** [comment]
@winder

**Review by bbroder-algo — APPROVED** [review]
better

**Pull request merged**
