### PR TITLE
Stateful teal test app read expect test

### PR DESCRIPTION
**Pull request by egieseke**
## Summary

Added an expect test for the `goal app read` command.  

## Test Plan

Ran `make integration`.

### CODE REVIEW

**Comment by egieseke** [comment]
> What is a difference between this `app read` test and existing `test/scripts/e2e_subs/e2e-app-bootloader.sh` ?

Very similar, except that the Wallet is specified.

**Comment by egieseke** [comment]
@algorandskiy I would like to commit this PR as is, and then create a new one to support adding the group transaction.  I created a new ticket to add the group transaction functionality here: https://github.com/algorand/go-algorand-internal/issues/668

**Comment by algorandskiy** [comment]
I do not see a reason to merge it as is since it duplicates existing `e2e-app-bootloader.sh` test.
The problem is this PR is based on #1291 that is merged so that `statefulTealAppReadTest.exp` is already in master.

**Comment by egieseke** [comment]
This duplicates #1291.

**Pull request closed without merging**
