### PR TITLE
1k+ assets (part 2)

### PR DESCRIPTION
**Pull request by algorandskiy**
## Summary

Introduce `ApplicationDbgLedger` interface to use in tealdbg and dryrun. This is to properly isolate internal `legderForCowBase` and allow its extension.

### CODE REVIEW

**Comment by tsachiherman** [comment]
it doesn't look like it was made "on top of the branch". Could you take another look ?

**Comment by algorandskiy** [comment]
Because part 1 was squashed during the merge and the common ancestor is the base branch again instead of part1 commits. This broke the entire idea of separate consequent PRs and all need to be re-created from different branches :(

**Comment by algorandskiy** [comment]
Updated. Now need to `rebase -i upstream/feature/1000-assets` and remove squashed commits manually after each squashed merge.

**Review by tsachiherman — APPROVED** [review]
looks good.

**Pull request merged**
