### PR TITLE
DevOps: Regen net.json for scenario2 test to include api endpoints for nodes.

### PR DESCRIPTION
**Pull request by egieseke**
## Summary

Regen scenario 2 net.json file to include API endpoints for nodes.

## Test Plan

Testing with scenario2 recipe with cicd perf pipeline.

### CODE REVIEW

**Review by nicholasguoalgorand — APPROVED** [review]
Looks good.

**Review by algojack — APPROVED** [review]

**Comment by algobarb** [comment]
Looks good, but does opening these API endpoints impact the amount of traffic going to telemetry? Just trying to still understand why Prometheus recently went down.

**Review by algobarb — APPROVED** [review]
Thanks for removing the NetAddress from custom and scenario2.

**Comment by egieseke** [comment]
> Looks good, but does opening these API endpoints impact the amount of traffic going to telemetry? Just trying to still understand why Prometheus recently went down.

These endpoints allow the bandwidth tool to communicate with the nodes and collect the bandwidth data.

**Pull request merged**
