### PR TITLE
use matrix for CircleCI config

### PR DESCRIPTION
**Pull request by cce**
## Summary

Based on the matrix job @algojack added in #2749, this turns the other per-platform jobs into matrix jobs too. The most significant change in this PR is switching from building in the home directory (/home/circleci on Linux and /Users/distiller on Mac) to instead build out of /opt/cibuild to make it easier for the matrix jobs to share configuration.

## Test Plan

It would be good to check that all the same tests are being run as before, perhaps by going through the build output manually or the artifacts (resulting JSON/XML files).

### CODE REVIEW

**Review by algobarb — APPROVED** [review]
Read through it and reviewed the CircleCI results. It seems good to me and it introduced me to yaml syntax for using `&ref_name` and `<<: *ref_name`. The extended use of matrices for the executors does reduce a lot of duplicate code.

I wonder how easy it will be for someone new to jump into and make changes to the config file later on and whether the YAML is enough or if we need any documentation on what we expect our CircleCI to currently do.

**Comment by cce** [comment]
Yes, I also didn't know that YAML syntax either until I saw it recently in [some CircleCI docs](https://circleci.com/docs/2.0/workflows/) and then read their YAML guide on [Anchors and aliases](https://circleci.com/docs/2.0/writing-yaml/#anchors-and-aliases).

**Comment by algojack** [comment]
lgtm, here's a good simple article on the << & and * https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd

**Review by algojack — APPROVED** [review]

**Comment by algojack** [comment]
@cce is the GIMME change in the second file on purpose? what does it do exactly?

**Comment by cce** [comment]
The original build.sh was downloading via curl the "gimme" script to ~/gimme.sh, so I changed it to check for a GIMME_INSTALL_DIR and use that, falling back to $HOME as before if it is not set. That made it possible for the matrix build not to be so dependent on the value of $HOME.

**Pull request merged**
