### PR TITLE
Cleanup evalAux

### PR DESCRIPTION
**Pull request by algobolson**
Simplify ledger data storage by removing 'evalAux' field which hasn't been used since before 1.0

### CODE REVIEW

**Comment by algobolson** [comment]
This doesn't change the database schema for existing nodes, it just stops writing an empty struct into a column we never use, and stops fetching it back from the database. For a new node the column wouldn't exist. For an existing node the column is full of empty structs we can ignore.

**Comment by tsachiherman** [comment]
> This doesn't change the database schema for existing nodes, it just stops writing an empty struct into a column we never use, and stops fetching it back from the database. For a new node the column wouldn't exist. For an existing node the column is full of empty structs we can ignore.

Right. but what happen if we now try to add a column to the schema. And that column happen to have the same name. It will execute correctly on some node, and fail on others. And given that it's deleted from the source code, we have no "memory" of the existence of this column.

**Comment by tsachiherman** [comment]
btw - I completely agree that we should remove this column from the `insert` statements.

**Comment by algoradam** [comment]
I think this shouldn't require a protocol upgrade since it doesn't change block evaluation at all. If we're worried we might forget and accidentally add an "auxdata" column to the schema sometime before we next upgrade the protocol, we can leave a comment in the code as a reminder not to use that name.

**Comment by algobolson** [comment]
added comment noting the removal or vestigial presence of the auxdata column

**Pull request merged**
