### PR TITLE
Add swagger to go mod tracking.

### PR DESCRIPTION
**Pull request by derbear**
See https://github.com/go-modules-by-example/index/blob/master/010_tools/README.md

Perhaps we should change scripts/check_deps.sh to use `go install` instead of `go get`--not sure if that makes a difference.

### CODE REVIEW

**Comment by zeldovich** [comment]
Is this to enforce a specific version of swagger to be installed by `scripts/check_deps.sh`?

I'm not sure how successful we will be, because the user might install a different version afterwards.

But, I think it would suffice to change `GO111MODULE=off` to `GO111MODULE=on` in `scripts/check_deps.sh` and `scripts/configure_dev-deps.sh`.  And we shouldn't need this `tools/tools.go`.

**Comment by winder** [comment]
@derbear should we add `GO111MODULE=on` as well?

**Comment by winder** [comment]
Lets just close this ticket, we're moving away from `go-swagger`

**Comment by derbear** [comment]
> Lets just close this ticket, we're moving away from go-swagger

Sounds good.

**Pull request closed without merging**
