### PR TITLE
docs: add 'bug' label, remove emoji, log at end

### PR DESCRIPTION
**Pull request by abebeos**
trivial

## Test Plan

* merge, look manually

### CODE REVIEW

**Comment by algorandskiy** [comment]
Closing as no activity/interest in two weeks.

**Comment by bbroder-algo** [comment]
I think you're right there could be some work in the labels area (not just the emoji or renaming) but probably should be the issue level at the moment.

**Comment by algorandskiy** [comment]
> Get serious, or ask someone to take away your triage rights (if you can't control yourself).

I'm trying man, trying

**Comment by abebeos** [comment]
> > Get serious, or ask someone to take away your triage rights (if you can't control yourself).
> 
> I'm trying man, trying

- You can't do everything yourself
- you need more core-devs
- you need more contribution

Follow-up https://github.com/algorand/go-algorand/pull/5322

**Pull request closed without merging**
