### PR TITLE
goal: allow for relative dataDir via -d cmd option

### LINKED ISSUE #589: goal -d directory is not recognized if the directory is also pwd and using '.' to refer to it
~/node/testnetdata
 $ cd Node
~/node/testnetdata/Node
 $ goal -d ../Node/  wallet  -f default 
could not make cachedir: mkdir Node/goal.cache: no such file or directory
~/node/testnetdata/Node
 $ cd ..
~/node/testnetdata
 $ goal -d Node/  wallet  -f default 
Set wallet 'default' to be the default wallet
~/node/testnetdata

### PR DESCRIPTION
**Pull request by abebeos**
## Summary

Allow relative data-dir, as described within #589

## Test Plan

existent tests pass, added some more tests

```sh
go test -v ./cmd/goal
```

### CODE REVIEW

**Comment by abebeos** [comment]
@algorandskiy , the Ci complains...

>Label error. Requires exactly 1 of: New Feature, Enhancement, Bug-Fix, Not-Yet-Enabled, Skip-Release-Notes. Found: user-facing, external contribution

**Review by algorandskiy — APPROVED** [review]
I'd make `resolveDataDir` a function taking dirs as its argument, and update `cmd/algocfg/datadir.go` as well, and probably move it to `cmd/utils`. But this also LGTM

**Comment by abebeos** [comment]
> I'd make `resolveDataDir` a function taking dirs as its argument, and update `cmd/algocfg/datadir.go` as well, and probably move it to `cmd/utils`. 

I did not notice the code-duplication, there are even more `resolveDataDir`  and other DataDir related duplicates.

Would prefer to handle them in a separate follow-up issue/PR (see #5068).

> But this also LGTM

Ty! (btw: fascinating fast PR processing!)

**Comment by algorandskiy** [comment]
closes #589

**Comment by abebeos** [comment]
@algorandskiy , somehow the github auto-close-issue did not trigger, still open: #589

**Pull request merged**
