### PR TITLE
use table, minor md fixes, remove distractions

### PR DESCRIPTION
**Pull request by abebeos**
trivial table/reformatting

* re `remove distractions`:
  - technical documentation (especially of such difficult systems) need to be free of distractions.

### CODE REVIEW

**Comment by algorandskiy** [comment]
Does not make sense for me

**Comment by abebeos** [comment]
> Does not make sense for me

Then maybe it makes sense to a core member?

@algorandskiy , I ask you to reopen the PR, so other members can review.

**Comment by algorandskiy** [comment]
With all due respect touching this document without any good reason has no value. If you would like to make a contribution please pick up something from open issues, I can give you few examples if interested.

**Comment by abebeos** [comment]
> With all due respect touching this document without any good reason has no value. 

This is your (completely unfounded) assessment, which is of no relevance in context of an open project.

I will not discuss "the necessity to stick to the markdown standard" with you, as you're obviously not competent enough to see this yourself.

> If you would like to make a contribution please pick up something from open issues, I can give you few examples if interested.

This requirement is not existent. You can try to enforce it on some junior devs.

I ask you again to reopen this PR, thus other members can review it.

**Pull request closed without merging**
