### PR TITLE
Add convertAddress tool.

### PR DESCRIPTION
**Pull request by winder**
## Summary

New tool: convertAddress
I share this tool with someone every few months, putting it in the repo along with some documentation should make it easier to share and encourage people to share it amongst themselves if it's useful.

Merge `debug` into `tools` to make it easier to organize these miscellaneous tools.

### CODE REVIEW

**Review by algorandskiy — APPROVED** [review]
Thank you Will!

**Comment by tsachiherman** [comment]
I would have placed it under `/debug` along with bunch of other debug tools that aren't being distributed with any of our packages.

**Comment by winder** [comment]
> I would have placed it under `/debug` along with bunch of other debug tools that aren't being distributed with any of our packages.

What do you think about moving `debug` into `tools`? As in tools for debugging algod.

**Comment by tsachiherman** [comment]
> > I would have placed it under `/debug` along with bunch of other debug tools that aren't being distributed with any of our packages.
> 
> What do you think about moving `debug` into `tools`? As in tools for debugging algod.

I like that idea.

**Review by algobarb — APPROVED** [review]

**Comment by winder** [comment]
> ... other debug tools that aren't being distributed with any of our packages.

We still distribute carpenter/coroner, looks like they build even in the new directory.

**Review by tsachiherman — APPROVED** [review]

**Pull request merged**
