### PR TITLE
feat: add support to display mnemonic discreetly for `algokey generate`

### PR DESCRIPTION
**Pull request by Halimao**
## Summary

This PR add support for displaying mnemonic discreetly.

- **New Features**
  - Addition of a new bool flag `generateIndiscreet`, used to disable new feature and printing mnemonic as old way.
  - Addition of discreet mnemonic display for `algokey generate` in `cmd/algokey`.
  - Added functionality to print sensitive information discreetly to an alternate screen.

## Test Plan

- Add test `Test_printDiscreetly` for new function `printDiscreetly`
- Build new `algokey` binary and test in local machine

```shell
./algokey generate --indiscreet
```
image

```shell
./algokey generate
```
image
image

### CODE REVIEW

**Comment by Halimao** [comment]
If this pr LGTY, I will draft another prs for `algokey import` and `algokey export`

**Comment by Halimao** [comment]
@jasonpaulos @onetechnical Hi sir, could you please help me review this pr, thanks🙏

**Comment by gmalouf** [comment]
@Halimao taking a look internally

**Comment by gmalouf** [comment]
User deleted their account.

**Comment by Halimao** [comment]
> User deleted their account.

You must be kiding me…

I'm just take this "ghost" for funny.

**Comment by gmalouf** [comment]
@Halimao our mistake, we looked quick and thought you had deleted the account.

If we understand this PR correctly, the mnemonic is still displayed when you first run it - so people watching over you could see it. An alternative to this code change to could be to hit ^L on your keyboard in the terminal to hide the mnemonic right?

**Comment by Halimao** [comment]
> hit ^L on your keyboard
I'm afraid I can't agree with this. In some cases, `Ctrl+L` doesn't clear the output on the terminal, it could be easily recovered just by sliding up the mouse scroll wheel.

This pr is indeed not suitable in the case that someone is watching over you. If we wanna prevent displaying private information when someone is watching over us, there are still more things that need to be done IMO.

This pr aims to split the `public info` and `private info` displayed to the user automatically. It improves security somehow, shows the mnemonic to the user, and then closes the alternate screen. No one can recover from this PC anymore.

**Review by jannotti — COMMENTED** [review]
I don't like this change in behaviour. But if we we did want it, is there something wrong with this:
```
package main

import (
    "github.com/inancgumus/screen"
)

func main() {
    // Clears the screen
    screen.Clear()
}
```
Do we have any way to know which terminals this solution works in vs another solution? Do we have any way to know if it stops working in some subset of the million terminal emulators on million OSes?

**Comment by Halimao** [comment]
> // Clears the screen

Why should we clear the whole screen? I just wanna clear the secret information on the terminal.

> Do we have any way to know which terminals this solution works in vs another solution? Do we have any way to know if it stops working in some subset of the million terminal emulators on million OSes?

If we are concerned about the compatibility with all Oses, we could make `--indiscreet` default to `true`, so that this new feature won't affect current behavior. For someone using common OSes, and wanna to hide secret pieces of information, this pr will provide them with a convenient way.

**Comment by gmalouf** [comment]
> If we are concerned about the compatibility with all Oses, we could make `--indiscreet` default to `true`, so that this new feature won't affect current behavior. For someone using common OSes, and wanna to hide secret pieces of information, this pr will provide them with a convenient way.

This was in my initial comment, I would make the setting --discrete defaulting to false (so that true is enabling the hiding functionality). Definitely did not want to change default behavior for folks under them.

**Comment by Halimao** [comment]
> This was in my initial comment

Aha, sorry for missing this comment. 

I just updated `--indiscreet` option's default value to `true`. Thanks for your review

**Comment by gmalouf** [comment]
Hi @Halimao, do you mind rebasing off of master? Our license check is failing I think because we updated them all to 2024 after January 1.

**Comment by gmalouf** [comment]
There are also some linter warnings from reviewdog related to expected test structure:

```lint: Test_printDiscreetly: Add missing partition call to top of test```

**Comment by gmalouf** [comment]
@Halimao I just checked this out manually and tested it:

The default `algokey generate` is indiscreet, to get the discreetness you are looking for you have to do `algokey generate --indiscreet=false`.  I think the default behavior is correct (do not want to change the default for existing users), but I would rename your flag to `discreet` with it defaulted to false, then update your logic for when it is true. Alternatively, allowing one to simply have the `discreet` flag present to enable (without specifying a boolean) would be even better if the framework supports it. 

Side note: had to refresh myself on discrete vs discreet usage :)

**Comment by Halimao** [comment]
> @Halimao I just checked this out manually and tested it:
> 
> The default `algokey generate` is indiscreet, to get the discreetness you are looking for you have to do `algokey generate --indiscreet=false`. I think the default behavior is correct (do not want to change the default for existing users), but I would rename your flag to `discreet` with it defaulted to false, then update your logic for when it is true. Alternatively, allowing one to simply have the `discreet` flag present to enable (without specifying a boolean) would be even better if the framework supports it.
> 
> Side note: had to refresh myself on discrete vs discreet usage :)

Addressed~

**Review by gmalouf — APPROVED** [review]
Thanks for making the changes, looks good.

**Review by jasonpaulos — APPROVED** [review]
Seems useful, and I confirmed locally that it works as intended

**Pull request merged**
