### PR TITLE
Brice/fix deploy linux

### PR DESCRIPTION
**Pull request by bricerisingalgorand**
## Summary

This removes an seemingly unnecessary cd to the parent directory of our project root that was causing huge docker build times

## Test Plan

Pavel is going to test it since he uses this script

### CODE REVIEW

**Comment by pzbitskiy** [comment]
The test is on my list

**Comment by pzbitskiy** [comment]
@bricerisingalgorand the command
```
./scripts/create_and_deploy_recipe.sh -c pavel-s1 --recipe test/testdata/deployednettemplates/recipes/scenario1/recipe.json -r ~/networks/pavel-s1
```
fails with
```
cd crypto/libsodium-fork && \
	test ! -e Makefile || make clean
rm -rf crypto/lib
tmp
tmp/pavel-brice-check
/bin/sh: 1: tmp/pavel-brice-check/deploy_linux_version_exec.sh: not found
The command '/bin/sh -c scripts/configure_dev-deps.sh && make deps && make clean && find tmp && tmp/pavel-brice-check/deploy_linux_version_exec.sh' returned a non-zero code: 127
```

Seems like `scripts/deploy_linux_version.sh` wants to have tmp inside the container.

**Comment by pzbitskiy** [comment]
Removing this from `.dockerignore` helps
```
# Exclude our local temp directory
tmp/
 
# Exclude certain build artifacts
gen/devnet/
gen/testnet/
gen/mainnet/
gen/betanet/
```

and then it fails with
```
./daemon/kmd/lib/kmdapi/bundle_swagger_json.sh
go install  --tags "sqlite_unlock_notify sqlite_omit_load_extension osusergo netgo static_build" -buildmode pie -ldflags="-X github.com/algorand/go-algorand/config.BuildNumber=61623 -X github.com/algorand/go-algorand/config.CommitHash=e9d7fee9+ -X github.com/algorand/go-algorand/config.Branch=check-brice -X github.com/algorand/go-algorand/config.DefaultDeadlock=enable -extldflags \"-static-libstdc++ -static-libgcc -static\" -X github.com/algorand/go-algorand/config.Channel=pavel-brice-check" ./...
# github.com/algorand/go-algorand/crypto
crypto/lib/libsodium.a(libsodium_la-salsa20_xmm6.o):(.data.rel+0x0): undefined reference to `stream_salsa20_xmm6'
crypto/lib/libsodium.a(libsodium_la-salsa20_xmm6.o):(.data.rel+0x8): undefined reference to `stream_salsa20_xmm6_xor_ic'
crypto/lib/libsodium.a(libsodium_la-curve25519_sandy2x.o): In function `crypto_scalarmult_curve25519_sandy2x_base':
crypto/libsodium-fork/src/libsodium/crypto_scalarmult/curve25519/sandy2x/curve25519_sandy2x.c:87: undefined reference to `crypto_scalarmult_curve25519_sandy2x_ladder_base'

Makefile:151: recipe for target 'buildsrc' failed

```

**Comment by tsachiherman** [comment]
I wasn't able to verify the issue observed by @pzbitskiy, I'll let him conduct few more tests to determine if it's an environment issue or not.

**Comment by bricerisingalgorand** [comment]
@tsachiherman Could you merge this one if everything looks good?

**Pull request merged**
