### PR TITLE
Disable compact certs and auction tests

### PR DESCRIPTION
**Pull request by bricerisingalgorand**
## Summary

They need work and shouldn't block our releases since they features aren't currently in use/enabled

## Test Plan

I ran these tests locally and saw that they all got skipped

### CODE REVIEW

**Comment by tsachiherman** [comment]
I'm ok with these changes, however, i would prefer to see the auction test along with the auction code being removed from go-algorand. Could you reach out to @algoidan , as he might be looking into that ?

Disabling the compact cert test is fine regardless.

**Review by onetechnical — APPROVED** [review]
Idan isn't actively working on this, but may in the future. I think this is fine for now.

**Comment by onetechnical** [comment]
Can you also make sure to add a ticket to re-enable and debug compact cert code?

**Review by egieseke — APPROVED** [review]
Looks good.

**Pull request merged**
