### PR TITLE
docs: add titles of subsystems, minor md fixes

### PR DESCRIPTION
**Pull request by abebeos**
trivial

### CODE REVIEW

**Review by bbroder-algo — APPROVED** [review]
better

**Comment by abebeos** [comment]
@bbroder-algo

**Comment by bbroder-algo** [comment]
> @bbroder-algo

yes?

**Comment by abebeos** [comment]
> > @bbroder-algo
> 
> yes?

Quiz:

What could a no-comment ping imply, given that

* this trivial PR is 2 weeks old
* only one review happened
* two reviews are needed
* I cannot trigger a review-request myself

?

**Comment by bbroder-algo** [comment]
sorry.  I have no control over other reviewers.

**Pull request merged**
