### PR TITLE
build: update go-sqlite3 dependency

### PR DESCRIPTION
**Pull request by zeldovich**
The version of go-sqlite3 we are currently using (v1.10.0) generates a warning from the C compiler on many go commands (like go build, go test, go vet, etc):

    # github.com/mattn/go-sqlite3
    sqlite3-binding.c: In function ‘sqlite3SelectNew’:
    sqlite3-binding.c:123303:10: warning: function may return address of local variable [-Wreturn-local-addr]
    123303 |   return pNew;
           |          ^~~~
    sqlite3-binding.c:123263:10: note: declared here
    123263 |   Select standin;
           |          ^~~~~~~

This change updates go-sqlite3 to the latest version (v1.14.16), which was fixed to avoid this warning; see:

    https://github.com/mattn/go-sqlite3/issues/803
    https://sqlite.org/forum/forumpost/e39020f82d7d510ea4d4a08ae370ca8df061c8b91884c82fda4897853faa2096

### CODE REVIEW

**Comment by algorandskiy** [comment]
Please do not merge, I want to do through all changelog items to ensure there is no new hidden gems in the driver.

**Comment by algorandskiy** [comment]
SQLite updated from 3.28.0 to 3.39.4, its change log: https://www.sqlite.org/changes.html
Possible affecting us things are:
1. INSERT and UPDATE statements now always apply [column affinity](https://www.sqlite.org/datatype3.html#affinity) before computing [CHECK constraints](https://www.sqlite.org/lang_createtable.html#ckconst). This bug fix could, in theory, cause problems for legacy databases with unorthodox CHECK constraints the require the input type for an INSERT is different from the declared column type. See ticket [86ba67afafded936](https://sqlite.org/src/info/86ba67afafded936) for more information.
2. The [BEGIN IMMEDIATE](https://www.sqlite.org/lang_transaction.html#immediate) and [BEGIN EXCLUSIVE](https://www.sqlite.org/lang_transaction.html#immediate) commands now work even if one or more attached database files are read-only.
3. Multiple user-discovered problems with the new Bloom filter optimization
4. Regressions fixed in post 3.39.4 releases:
    - Fix a potential infinite loop in the [memsys5](https://www.sqlite.org/malloc.html#memsys5) alternative memory allocator. This bug was introduced by a performance optimization in version 3.39.0.
    - Fix various obscure bugs reported by the user community. See the [timeline of changes](https://sqlite.org/src/timeline?from=version-3.41.0&to=version-3.41.1) for details.
    - Multiple fixes for reads past the end of memory buffers (NB: reads not writes) in the following circumstances:

Overall, there are bunch of bugfixes and perf improvements like
 - Improved performance of [WAL mode](https://www.sqlite.org/wal.html) locking primitives in cases where there are hundreds of connections all accessing the same database file at once.
 - Added support for [ALTER TABLE DROP COLUMN](https://www.sqlite.org/lang_altertable.html#altertabdropcol).
 - Improvement to the [EXPLAIN QUERY PLAN](https://www.sqlite.org/eqp.html) output to make it easier to understand.
 - [STRICT tables](https://www.sqlite.org/stricttables.html) provide a prescriptive style of data type management, for developers who prefer that kind of thing.
 - Add (long overdue) support for [RIGHT and FULL OUTER JOIN](https://www.sqlite.org/lang_select.html#rjoin).

The go-sqlite3 driver has bug fixes and a single virtual tables feature. Full log https://github.com/mattn/go-sqlite3/compare/v1.10.0...v1.14.16

**Review by algorandskiy — APPROVED** [review]
@zeldovich could you re-merge/rebase master to resolve conflicts?

**Review by algorandskiy — DISMISSED** [review]

**Review by algorandskiy — APPROVED** [review]

**Comment by winder** [comment]
My understanding is that sqlite table organization is very important to how catchpoints are generated. @algorandskiy @cce are you confident that we have sufficient test coverage in this area?

I'm running a fast catchup with this branchas a sanity check.

**Comment by algorandskiy** [comment]
I reviewed all commits to the driver and sqlite3 changelog. Also checked labels for betanet catchpoints vs known ones, all clear.

**Review by winder — APPROVED** [review]
LGTM.

The following catchpoints worked with no issue:
* betanet: 28820000#DBX6KZRAUFW77MWHQR6XGOUEHUAE5NA5BIR3OXLDRQIO66VYJLHQ
* testnet: 32200000#AXYFV7SXBVDVPASSROYWLL6UTINNMMCVTSCEUYIDYG5VZFXVF4TA
* mainnet: 31340000#VSHDY2LHOIIKN6AWDQ2ZJYAIDNTZLSIJMZVUJUXWUNU7MQWECY5A

**Pull request merged**
