### PR TITLE
Update go files to have license range of 2021

### PR DESCRIPTION
**Pull request by tsachiherman**
## Summary

Update the license range from 2019-2020 to 2019-2021.

## Test Plan

No tests updates here, as this is only an in-code comment. The testing for this is done via the license check shell script.

### CODE REVIEW

**Review by pzbitskiy — CHANGES_REQUESTED** [review]
I disagree. Let's update the checker script and allow 2019-202x

**Comment by tsachiherman** [comment]
> I disagree. Let's update the checker script and allow 2019-202x

Both Adam and myself have looked into that in the past.
The goal here is to get the broadest legal protection while reducing the potential licensing ambiguity to the minimum.

I know that it looks like a tidious thing, but if you'll evaluate the actual cost, you'll find that it won't realy make a difference. 

Btw - I think that it's reasonable to convert a off-by-one year to be a warning rather then a build failuire.

**Comment by brianolson** [comment]
Do we allow 20xx-2021 ? It seems wrong to me to claim 2019 copyright on a file that was created during 2020.

**Review by onetechnical — APPROVED** [review]
Looks simple enough. I wonder if we could automate this.

**Comment by tsachiherman** [comment]
> Do we allow 20xx-2021 ? It seems wrong to me to claim 2019 copyright on a file that was created during 2020.

It would be reasonable to have it claim "2019" if one could say he was working on this "feature" for a very long time, right ?
( i.e. it doesn't have to be the "publishing date" )

It wouldn't be wrong to have some of the files start at 2021-2021, for instance. however, I think that there is real added value ( and please correct me if I'm wrong here ) in making it more flexible that we absolutely need to get legal coverage that we want.

The fact that the build "fail" might sounds like a bad thing, but it's more of a reminder to us, not a really a product failure. ( keep in mind that it would only fail on travis builds.. not locally )

**Pull request merged**
