### PR TITLE
Add support for building 64-bit ARM (RPi)

### PR DESCRIPTION
**Pull request by Karmastic**
Simple update given the existing 32-bit arm support

### CODE REVIEW

**Comment by tsachiherman** [comment]
@algobolson If you think that this one is good, I suggest we'll merge this in.
( or just close it )

**Comment by algobolson** [comment]
I'm a little curious if this enables ARM64 usage on AWS ARM EC2 instances. I definitely don't have time to test RasPi myself right now.

**Comment by tsachiherman** [comment]
> I'm a little curious if this enables ARM64 usage on AWS ARM EC2 instances. I definitely don't have time to test RasPi myself right now.

It definitely seems to be a prerequisite for that. But I don't think that would be enough.

**Comment by giovannirco** [comment]
> I'm a little curious if this enables ARM64 usage on AWS ARM EC2 instances. I definitely don't have time to test RasPi myself right now.

Hey, did you try it on aws?

**Pull request merged**
