### PR TITLE
AVM: Only update the bytec disassembleState for bytecblock opcodes

### PR DESCRIPTION
**Pull request by nullun**
During disassembly, if a contract includes a `pushbytess` opcode after the `bytecblock`, it will no longer overwrite the bytec disassembleState. This resulted in incorrect or missing comments for disassembled `bytec` opcodes.

Of course, there is still the issue of someone using `bytecblock` multiple times, however that's easier to identify. This threw me for a while.

Test program:
```
cat test.teal                                                  
#pragma version 10
bytecblock 0x6869 0x414243 0x74657374 0x666f7572 0x6c617374
bytec_0
bytec_1
bytec_2
bytec_3
bytec 4
pushbytess 0x6576696c
bytec_0
bytec_1
bytec_2
bytec_3
bytec 4
```
Before:
```
goal clerk compile test.teal -o - | goal clerk compile -D - 
#pragma version 10
bytecblock 0x6869 0x414243 0x74657374 0x666f7572 0x6c617374
bytec_0 // "hi"
bytec_1 // "ABC"
bytec_2 // "test"
bytec_3 // "four"
bytec 4 // "last"
pushbytess 0x6576696c
bytec_0 // "evil"
bytec_1
bytec_2
bytec_3
bytec 4
```
After:
```
goal clerk compile test.teal -o - | goal clerk compile -D - 
#pragma version 10
bytecblock 0x6869 0x414243 0x74657374 0x666f7572 0x6c617374
bytec_0 // "hi"
bytec_1 // "ABC"
bytec_2 // "test"
bytec_3 // "four"
bytec 4 // "last"
pushbytess 0x6576696c
bytec_0 // "hi"
bytec_1 // "ABC"
bytec_2 // "test"
bytec_3 // "four"
bytec 4 // "last"
```

### CODE REVIEW

**Comment by jannotti** [comment]
I assume we have the same problem for `intc`, with `pushints`?

**Comment by nullun** [comment]
> I assume we have the same problem for `intc`, with `pushints`?

Good thinking! Let me take a look and add the change for that too.

**Comment by nullun** [comment]
As I did before, here was my local test.

Test  program:
```
cat test.teal 
#pragma version 10
intcblock 0 1 2 3 4 5
intc_0
intc_1
intc_2
intc_3
intc 4
pushints 6
intc_0
intc_1
intc_2
intc_3
intc 4
```

Before:
```
goal clerk compile test.teal -o - | goal clerk compile -D - 
#pragma version 10
intcblock 0 1 2 3 4 5
intc_0 // 0
intc_1 // 1
intc_2 // 2
intc_3 // 3
intc 4 // 4
pushints 6
intc_0 // 6
intc_1
intc_2
intc_3
intc 4
```

After:
```
goal clerk compile test.teal -o - | goal clerk compile -D -
#pragma version 10
intcblock 0 1 2 3 4 5
intc_0 // 0
intc_1 // 1
intc_2 // 2
intc_3 // 3
intc 4 // 4
pushints 6
intc_0 // 0
intc_1 // 1
intc_2 // 2
intc_3 // 3
intc 4 // 4
```

**Review by jannotti — DISMISSED** [review]
Love it. I'll wrangle another review.

**Review by jannotti — APPROVED** [review]

**Pull request merged**
