### PR TITLE
Add some TEAL3 opcodes

### PR DESCRIPTION
**Pull request by jeapostrophe**
I don't expect you to take this as-is, without addressing #1633, and adding a version 3, but I am working on a program and these instructions are very useful for me.

For example, I have an example program that verifies the rules of a simple game in a TEAL contract. My original compiler as of Monday used ~6000 bytes for the program, then I fixed a dumb thing and got it to 3262 bytes, but then I did a lot of aggressive optimizations over the last few days and got it down to 946 bytes, but I expect the argument size to be 77 bytes, so `946 + 77 = 1023`, so I needed to do something else. These new instructions, especially `assert` and `ite` drop this program down to 864 bytes, which is good for me.

(You can get `assert` via `bz fail; .....; fail: int 0; return <EOF>`, but `bz` is three bytes, so that's a lot when most of a TEAL program is checking or failing.)

(You can get `cond; true; false; ite` via `cond; bz l_false; true; bz l_join; false; l_join:` which is 6 bytes vs 1, so it's a pretty decent win. `ite` is only useful if `true` and `false` are simple, so it is like a conditional move or the `?:` operator.)

(Swap is a big win in size, because `store 0; store 1; load 0; load 1` is 8 bytes plus pinning two slots.)

### CODE REVIEW

**Comment by jeapostrophe** [comment]
p.s. I will look into how to add opcode tests to the suite and put in tests for these... it wasn't obvious to me so I haven't yet figured it out.

**Comment by pbennett** [comment]
Adding more powerful opcodes to TEAL would be fantastic.  
I'd recommend you add BenchmarkXXXX functions which exercise these opcodes, so their computational impact can be assessed.  In particular, a benchmark with a 'real' program created from Reach, and two sub-benchmarks, one using the TEAL2 opcodes, and another using the TEAL3 opcodes would be an excellent starting point.  
Comparing the two would trivial, and effective in showing the value and usefulness of a few more expressive opcodes (or not! real data matters...)

Here's a nice example of sub-benchmarks if you're not familiar:
https://medium.com/justforfunc/analyzing-the-performance-of-go-functions-with-benchmarks-60b8162e61c6

**Comment by jeapostrophe** [comment]
Thanks Patrick, just a quick FYI, these instructions are not about making the TEAL program faster, they are all about conserving byte size, because of the strict 1000 byte limit on the program and its arguments. Your comment makes me think you're thinking of speed. Without these instructions, I don't know how to compile the Reach program to be small enough because it is just too big, so I can't benchmark it at all in TEAL2, ya know?

**Comment by pbennett** [comment]
I think speed has to always be a consideration.  1000+TPS (and with work ongoing to increase that), means that those transactions need to be contracts as well and perform comparably.  Just requiring fewer bytes for the same operations could impact the performance in numerous, and not always obvious ways.  Performance could be significantly improved.
However, if performance is significantly impacted, that could be a problem unto itself.  If it means certain code isn't possible at all because of size restrictions though, I think that's a reasonable argument to make in return.
If performance is unchanged, yet size reduced, or even better, if performance is increased - both make it IMO a no-brainer.

**Comment by jeapostrophe** [comment]
I just added four more instructions that are simplified versions of `substring/strsplice` for bytes. This cuts another 100-ish bytes of my current program and finally gets it + arguments below the limit. (I originally thought the arguments were 77 bytes, but actually they were 209 for one step, so I needed to make some more cuts.)

It would probably be nice(r) to have a `bitset/get` that worked on bytes, but when I was implementing it, I felt that code was too complicated to work on both ints and bytes, so this was simpler and serves the purpose well.

**Comment by brianolson** [comment]
Your assert could be a couple bytes shorter using the `err` op. `...; bz fail; ...; fail: err`

**Comment by jannotti** [comment]
I'm going to close this as everything (except splice) is in teal3. I think teal4 will make splice less important (as functions will be possible)

**Pull request closed without merging**
