### PR TITLE
Fetch creators in a batch in `EvalForIndexer()`

### PR DESCRIPTION
**Pull request by tolikzinovyev**
## Summary

With this change, Indexer is able to preload creators of most assets and apps in a batch.

## Test Plan

Indexer import TPS goes up 10% when used with Amazon Aurora.

### CODE REVIEW

**Review by tsachiherman — CHANGES_REQUESTED** [review]
I think that the functionality here isn't incorrect - but rather misplaced. This optimization is indexer specific, and as such, should live within the indexer code base. The evelIndexer should contain the interfacing between the two, and be limited to that.

If needed, extending the `indexerLedgerForEval` does make sense here.

**Comment by tolikzinovyev** [comment]
This is what we did with accounts, and I think this is the right place to preload things since knowing what to preload is highly specific to the evaluator. Also, having two caches (in cow base and indexer) storing the same data isn't pretty. How would I extend `indexerLedgerForEval`?

**Comment by tsachiherman** [comment]
no, I was not suggesting having another cache in the indexer repo. I was saying the the indexer repo should provide a method that would analyze a block, and return a pre-init set of values for the the two caches. The `EvalForIndexer` should take these arrays/maps and populate the cowbase with them.

**Comment by tolikzinovyev** [comment]
I think this will be convoluted. Eval should know what to preload, so why wouldn't it just do that?

**Comment by tsachiherman** [comment]
If this was a shared functionality, then I would agree with you. However, since the indexer is the only consumer of this preloading, I think that it would be better for the indexer to figure out what need to be preloaded, load that, and then provide that information to the evaluator.

**Comment by tolikzinovyev** [comment]
Are you proposing this interaction? Indexer's `AddBlock()` -> go-algorand's `FindWhatToPreload()` -> preload in indexer -> go-algorand's `EvalIndexer()` -> indexer writes the state delta. Seems too much going back and forth. The alternative is to have `FindWhatToPreload()` in Indexer, but then this eval-specific knowledge is far from eval.

**Comment by tsachiherman** [comment]
> go-algorand's `FindWhatToPreload()`

why ? I was thinking of:
- AddBlock() < indexer >
- PreloadResources < indexer >
   - FindWhatToPreload
   - LoadResources
- EvalIndexer(..., <resources>)

**Comment by tolikzinovyev** [comment]
So the second option then. I guess it's ok, it's just now the accounting logic of `FindWhatToPreload()` is not part of eval.

**Pull request closed without merging**
