### PR TITLE
CircleCI: Separated jobs to remove parallelism in single self-hosted runner

### PR DESCRIPTION
**Pull request by algobarb**
## Summary

We are using a self-hosted runner for mac arm64 in CircleCI and we only have one machine to test with. CircleCI tests that use the self-hosted runner gets queued up to run one at a time on the machine.

When we set parallelism to 4 in test_nightly, the 4 "parallels" don't actually work in parallel. Instead, we see that each "parallel" run happens one after the other because we don't have 4 machines to split the work on. This means additional time for set up is lost during each parallel when we only have one self-hosted runner.

### Impact
This change saves around 10 minutes in "rel/*" tests and help speed up the queue for other CircleCI tests in our environment that may be waiting for the self-hosted runner.
Removed parallelism in the following jobs:
1. mac_arm64_test_nightly 
  - For some reason, the mac_arm64_test_nightly_verification was failing because of unintentionally skipped tests due to partitioning, so I set the parallelism to 2, (**before with parallelism==4**: 1h 0m 28s ; **after with parallelism==2**: 55m 2s). So it still saves about 5 minutes.
  - (**if parallelism was set to 0**: 52m 4s) Save: ~8min~~
3. mac_arm64_e2e_expect_nightly (**before**: 22m 25s ; **after**: 19m 49s) Save: ~2-3min
4. mac_arm64_integration (**before**: 1h 6m, **after**: 44m 38s), Save: ~22 min
Total Approx time saved in the test alone (not including saving on all the switching and queue time on our single self-hosted runner): ~30min

If there's a way to make this more DRY, let me know. I couldn't find a way to make parallelism based on a conditional.

## Test Plan

Checked `circleci config validate` to make sure it's a valid config file.
I triggered the nightly test although I expect amd64_e2e_subs_nightly test to fail on the fork because it is looking for CircleCI contexts for an upload step. I mostly focused on the run times for the mac_arm64 nightly jobs.

### CODE REVIEW

**Review by excalq — DISMISSED** [review]

**Review by algojack — COMMENTED** [review]
We should remove matrix-nightly from Line 81 if we want to go this way

**Review by algojack — COMMENTED** [review]
I would suggest that this doesn't save us much time (especially on nightlies) but it does create duplication of code, and we would have to change things in more places.
I would also suggest moving off of self hosted runner, which we have a ticket for.

**Comment by algobarb** [comment]
> I would suggest that this doesn't save us much time (especially on nightlies) but it does create duplication of code, and we would have to change things in more places. I would also suggest moving off of self hosted runner, which we have a ticket for.

Yes it's unfortunate that I couldn't figure out how to parameterize the "parallelism" part and I agree there's a lot of duplicate code. As for moving off of self-hosted runners, CircleCI uses AWS dedicated metal instances, so the issue will still be the same as self-hosted runners in regards to parallelism. Here's a part of the CircleCI documentation on metal AWS machines:

> Each account has a maximum of one dedicated host by default. You can increase the maximum number by contacting [CircleCI support](https://support.circleci.com/hc/en-us/requests/new)
> , or your account representative.
> 
> Once a dedicated host has been allocated, you have exclusive access to it for a minimum of 24 hours. If the dedicated host is already in use when a job is kicked off, the job is queued until the host becomes available, unless you have increased your dedicated host limit.
https://circleci.com/docs/dedicated-hosts-macos/

**Comment by algobarb** [comment]
> We should remove matrix-nightly from Line 81 if we want to go this way

I think you're right, let me take a look.

**Comment by algobarb** [comment]
> We should remove matrix-nightly from Line 81 if we want to go this way

I did miss that integration_nightly was also setting parallelism to 4... After adding in mac_arm65_integration_nightly separately (without parallelism), we save another 20+ minutes. But this is a lot of extra code... Line 81's reference to `matrix-nightly` is still used for e2e_subs_nightly and upload_binaries.

I think the results illustrate the problem, but I'm not sure if there's a way to do this with less duplicate code.

**Comment by algobarb** [comment]
Hmmm this is failing in the nightly verification test. Maybe we need to have the partitions in the mac_arm64_test_nightly for these tests?
```
github.com/algorand/go-algorand/data/transactions/verify TestStreamVerifierCases -- skipped unintentionally. (due to partitiontest.PartitionTest() being called twice?)
```
https://app.circleci.com/pipelines/github/algorand/go-algorand/11615/workflows/a59959f1-3ad4-4e04-af24-65486b662db2

**Comment by algojack** [comment]
so i'm not sure why the validation step fails. I think we can ask devs to help with this one.

But for less code duplication, we can only change the workflows, (duplicate workflows like you did) and pass a parallelism parameter to the jobs (don't duplicate the jobs).

**Comment by algojack** [comment]
we can also not duplicate workflows, but in the job set parallelism based on a check if it's mac arm or not https://discuss.circleci.com/t/if-else-parameter-syntax/42815

**Comment by jsgranados** [comment]
Blocked due to switch in priority. Will re-visit when team has time. 
Ticket implementation will help to reduce release times by ~30m

What we would like to do is to prioritize parametrization of parallelism when running our tests

**Comment by jsgranados** [comment]
Blocked due to switch in priority. Will re-visit when team has time. 
Ticket implementation will help to reduce release times by ~30m

What we would like to do is to prioritize parametrization of parallelism when running our tests

**Comment by algobarb** [comment]
Closing this PR until we have time to look into this again.

**Pull request closed without merging**
