### PR TITLE
[GOAL2-777] Catchup performance : avoid retrying unless previous block was retrieved

### PR DESCRIPTION
**Pull request by tsachiherman**
Existing code would retry retrieving a block regardless of whether the previous block was retrieved successfully. While (functionally) it won't hurt to make the subsequent attempt, it generate excessive network traffic when the first block retrieval is being delayed.

We want to keep the happy path retrieve blocks as fast as possible, while slowing down once we ran into network failures.

### CODE REVIEW

**Comment by tsachiherman** [comment]
Just a small note - these changes are only optimization. I have no reason to believe that the existing network would not be able to sustain the expected load ( by order of magnitude )

**Comment by Vervious** [comment]
I am worried that this might adversely affect parallelism: consider the following scenario:

We call fetchAndWrite on the next 50 blocks; all the fetchers (in parallel) hit the same peer X for blocks r + 1, r + 2, ... r + 50; X happens to be misconfigured, so all of these requests fail. 

But now, all fifty requests are serialized, waiting for seed loopbacks, because of one faulty peer, and catchup is no longer parallelized until all 50 blocks are fetched.

Is this a problem? Let me think about it some more.

**Comment by zeldovich** [comment]
> I am worried that this might adversely affect parallelism: consider the following scenario:
> 
> We call fetchAndWrite on the next 50 blocks; all the fetchers (in parallel) hit the same peer X for blocks r + 1, r + 2, ... r + 50; X happens to be misconfigured, so all of these requests fail.
> 
> But now, all fifty requests are serialized, waiting for seed loopbacks, because of one faulty peer, and catchup is no longer parallelized until all 50 blocks are fetched.
> 
> Is this a problem? Let me think about it some more.

In this scenario, peer X will be taken out of the candidate peer list, and subsequent block fetches will be pipelined properly.

**Comment by Vervious** [comment]
> In this scenario, peer X will be taken out of the candidate peer list, and subsequent block fetches will be pipelined properly.

The peer list is checked before we call `client.GetBlockBytes`, and it seems possible that we could hit the same peer in parallel until a request errors.

That being said, I looked at the code again, and we select peers randomly. So probably it's ok.

**Pull request merged**
