### PR TITLE
Add sqlite3 as a dependency

### PR DESCRIPTION
**Pull request by fabrice102**
## Summary

When running `make`, `sqlite3` is used but was not included as a dependency in:
* `scripts/check_deps.sh`
* `scripts/configure_dev.sh`

## Test Plan

Ran `scripts/configure_dev.sh` and `make` on macOS and Ubuntu 18.04.

### CODE REVIEW

**Comment by tsachiherman** [comment]
@bricerisingalgorand could you take a look on this one ?
I think that it looks legit, but it brings the questions - where did the sqlite3 on travis builds came from ?

**Comment by fabrice102** [comment]
It may be that `sqlite3` is included by default in Travis CI. Strangely enough, it does not appear on https://docs.travis-ci.com/user/reference/bionic/. However, https://docs.travis-ci.com/user/database-setup/#sqlite3 seems to imply that `sqlite3` is included by default.

**Comment by bricerisingalgorand** [comment]
That doc does appears to imply that it's there by default. It's interesting that the build also works on our remote builds as well, but maybe that was included in the machine image of the host. The travis job failed due to a race condition so I'll restart it

**Comment by tsachiherman** [comment]
> That doc does appears to imply that it's there by default. It's interesting that the build also works on our remote builds as well, but maybe that was included in the machine image of the host. The travis job failed due to a race condition so I'll restart it

I think that the failure was due to
```./test/scripts/e2e.sh: line 72: python3: command not found```

and that was caused because the internet has changed without your explicit approval...

last time it happened, I pinned the boost version ( see ./scripts/travis/configure_dev.sh ). You might want to try and figure out which component has changed and pin the modified component.

**Comment by fabrice102** [comment]
Indeed, that seems to be a similar issue as #669:
```
==> Installing libxml2 dependency: python
==> Downloading https://homebrew.bintray.com/bottles/python-3.7.6_1.mojave.bottl
==> Downloading from https://akamai.bintray.com/64/643d627c2b4fc03a3286c397d2992
######################################################################## 100.0%
==> Pouring python-3.7.6_1.mojave.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink Frameworks/Python.framework/Headers
Target /usr/local/Frameworks/Python.framework/Headers
is a symlink belonging to python@2. You can unlink it:
  brew unlink python@2
To force the link and overwrite all conflicting files:
  brew link --overwrite python
To list all files that would be deleted:
  brew link --overwrite --dry-run python
Possible conflicting files are:
/usr/local/Frameworks/Python.framework/Headers -> /usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Headers
/usr/local/Frameworks/Python.framework/Python -> /usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Python
/usr/local/Frameworks/Python.framework/Resources -> /usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Resources
/usr/local/Frameworks/Python.framework/Versions/Current -> /usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/Current
==> /usr/local/Cellar/python/3.7.6_1/bin/python3 -s setup.py --no-user-cfg insta
==> /usr/local/Cellar/python/3.7.6_1/bin/python3 -s setup.py --no-user-cfg insta
==> /usr/local/Cellar/python/3.7.6_1/bin/python3 -s setup.py --no-user-cfg insta
==> Caveats
Python has been installed as
  /usr/local/bin/python3
Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin
You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.7/site-packages
See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python/3.7.6_1: 3,977 files, 60.8MB
```

Since anyway `sqlite3` is included by default on macOS, I'm removing it from `scripts/configure_dev.sh`, and just keeping it in `scripts/check_deps.sh`

**Pull request merged**
