### PR TITLE
Telemetry: Remove unused TelemetryOperation

### PR DESCRIPTION
**Pull request by michaeldiamant**
Proposes removing what appears to be an unused telemetry functionality:  `TelemetryOperation`.

Since I found no usage, I'm wondering if it's defunct functionality.

### CODE REVIEW

**Review by brianolson — APPROVED** [review]
Yes. There are better ways to do this. If we need it in the future we should build the right thing at that time.

**Review by excalq — DISMISSED** [review]
The best programming language is red lines!
Thanks for doing a bit to clean up the hydra that is our telemetry code.

**Comment by michaeldiamant** [comment]
FYI - Merged in `master` to address conflict created by https://github.com/algorand/go-algorand/pull/4957.

**Review by brianolson — APPROVED** [review]
still good

**Pull request merged**
