### PR TITLE
Implement expect test for goal account dump

### PR DESCRIPTION
**Pull request by algorandskiy**
## Summary

Test goal account dump produces JSON or msgpack blob, and errs on invalid input

## Test Plan

This is a test

### CODE REVIEW

**Comment by algorandskiy** [comment]
I agree on 1 and 3 but 2 with testing all fields for expected values looks as overkill. `dump` is an as-is thin dumper of `BalanceRecord` data structure. In the same guess checking for `AppParams` makes sense since access to `AppParams` was one of reason of creation this command. Thank you for the feedback.

**Comment by algorandskiy** [comment]
@tsachiherman 
seems like we still have locking problem in accountdb - see the[ build log](https://travis-ci.com/github/algorand/go-algorand/jobs/364053023)
```
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 1429305 lock 0xc0444fae78
../util/db/dbutil.go:253 db.(*Accessor).atomic { commitLocker.Lock() } <<<<<
../util/db/dbutil.go:369 db.(*Accessor).AtomicCommitWriteLock { return db.atomic(fn, commitLocker, extras...) }
../util/db/dbutil.go:369 db.(*Accessor).AtomicCommitWriteLock { return db.atomic(fn, commitLocker, extras...) }
acctupdates.go:1100 ledger.(*accountUpdates).commitSyncer { au.commitRound(committedOffset.offset, committedOffset.dbRound, committedOffset.lookback) }
Have been trying to lock it again for more than 30s
goroutine 1429269 lock 0xc0444fae78
acctupdates.go:254 ledger.(*accountUpdates).lookup { au.accountsMu.RLock() } <<<<<
ledger.go:363 ledger.(*Ledger).Lookup { data, err := l.accts.lookup(rnd, addr, true) }
eval.go:250 ledger.startEvaluator { incentivePoolData, err := l.Lookup(eval.prevHeader.Round, poolAddr) }
eval.go:820 ledger.(*Ledger).eval { eval, err := startEvaluator(l, blk.BlockHeader, len(blk.Payset), validate, false) }
ledger.go:454 ledger.(*Ledger).AddBlock { updates, err := l.eval(context.Background(), blk, false, nil, nil) }
ledger_test.go:882 ledger.TestLedgerBlockHdrCaching { err := l.AddBlock(blk, agreement.Certificate{}) }
Here is what goroutine 1429305 doing now
goroutine 1429305 [runnable]:
github.com/algorand/go-algorand/ledger.(*accountUpdates).accountsUpdateBalances(0xc0444faad0, 0xc02b131650, 0xc02b1316e0, 0x0)
	/home/travis/gopath/src/github.com/algorand/go-algorand/ledger/acctupdates.go:1044 +0xef
github.com/algorand/go-algorand/ledger.(*accountUpdates).commitRound.func2(0x18ef1c0, 0xc0412a5920, 0xc040de5d80, 0xc0412a5920, 0xc0412a5920)
	/home/travis/gopath/src/github.com/algorand/go-algorand/ledger/acctupdates.go:1215 +0x42b
github.com/algorand/go-algorand/util/db.(*Accessor).atomic.func1(0x18ef1c0, 0xc0412a5920, 0xc040de5d80, 0x0, 0x0)
	/home/travis/gopath/src/github.com/algorand/go-algorand/util/db/dbutil.go:226 +0x97
github.com/algorand/go-algorand/util/db.(*Accessor).atomic(0xc0444fad28, 0xc0412810e0, 0x18e5f80, 0xc0444fae78, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/algorand/go-algorand/util/db/dbutil.go:311 +0xa9c
github.com/algorand/go-algorand/util/db.(*Accessor).AtomicCommitWriteLock(...)
	/home/travis/gopath/src/github.com/algorand/go-algorand/util/db/dbutil.go:369
github.com/algorand/go-algorand/ledger.(*accountUpdates).commitRound(0xc0444faad0, 0x1, 0x560, 0x140)
	/home/travis/gopath/src/github.com/algorand/go-algorand/ledger/acctupdates.go:1190 +0xbff
github.com/algorand/go-algorand/ledger.(*accountUpdates).commitSyncer(0xc0444faad0, 0xc0443eed80)
	/home/travis/gopath/src/github.com/algorand/go-algorand/ledger/acctupdates.go:1100 +0x62
created by github.com/algorand/go-algorand/ledger.(*accountUpdates).initializeFromDisk
	/home/travis/gopath/src/github.com/algorand/go-algorand/ledger/acctupdates.go:758 +0xc64
Other goroutines holding locks:
goroutine 1429269 lock a7
ledger.go:359 ledger.(*Ledger).Lookup { l.trackerMu.RLock() } <<<<<
eval.go:250 ledger.startEvaluator { incentivePoolData, err := l.Lookup(eval.prevHeader.Round, poolAddr) }
eval.go:820 ledger.(*Ledger).eval { eval, err := startEvaluator(l, blk.BlockHeader, len(blk.Payset), validate, false) }
ledger.go:454 ledger.(*Ledger).AddBlock { updates, err := l.eval(context.Background(), blk, false, nil, nil) }
ledger_test.go:882 ledger.TestLedgerBlockHdrCaching { err := l.AddBlock(blk, agreement.Certificate{}) }
```

**Comment by tsachiherman** [comment]
> @tsachiherman
> seems like we still have locking problem in accountdb - see the[ build log](https://travis-ci.com/github/algorand/go-algorand/jobs/364053023)
> 
> ```
> POTENTIAL DEADLOCK:
> Previous place where the lock was grabbed
> goroutine 1429305 lock 0xc0444fae78
> ../util/db/dbutil.go:253 db.(*Accessor).atomic { commitLocker.Lock() } <<<<<
> ../util/db/dbutil.go:369 db.(*Accessor).AtomicCommitWriteLock { return db.atomic(fn, commitLocker, extras...) }
> ../util/db/dbutil.go:369 db.(*Accessor).AtomicCommitWriteLock { return db.atomic(fn, commitLocker, extras...) }
> acctupdates.go:1100 ledger.(*accountUpdates).commitSyncer { au.commitRound(committedOffset.offset, committedOffset.dbRound, committedOffset.lookback) }
> Have been trying to lock it again for more than 30s
> goroutine 1429269 lock 0xc0444fae78
> acctupdates.go:254 ledger.(*accountUpdates).lookup { au.accountsMu.RLock() } <<<<<
> ledger.go:363 ledger.(*Ledger).Lookup { data, err := l.accts.lookup(rnd, addr, true) }
> eval.go:250 ledger.startEvaluator { incentivePoolData, err := l.Lookup(eval.prevHeader.Round, poolAddr) }
> eval.go:820 ledger.(*Ledger).eval { eval, err := startEvaluator(l, blk.BlockHeader, len(blk.Payset), validate, false) }
> ledger.go:454 ledger.(*Ledger).AddBlock { updates, err := l.eval(context.Background(), blk, false, nil, nil) }
> ledger_test.go:882 ledger.TestLedgerBlockHdrCaching { err := l.AddBlock(blk, agreement.Certificate{}) }
> Here is what goroutine 1429305 doing now
> goroutine 1429305 [runnable]:
> github.com/algorand/go-algorand/ledger.(*accountUpdates).accountsUpdateBalances(0xc0444faad0, 0xc02b131650, 0xc02b1316e0, 0x0)
> 	/home/travis/gopath/src/github.com/algorand/go-algorand/ledger/acctupdates.go:1044 +0xef
> github.com/algorand/go-algorand/ledger.(*accountUpdates).commitRound.func2(0x18ef1c0, 0xc0412a5920, 0xc040de5d80, 0xc0412a5920, 0xc0412a5920)
> 	/home/travis/gopath/src/github.com/algorand/go-algorand/ledger/acctupdates.go:1215 +0x42b
> github.com/algorand/go-algorand/util/db.(*Accessor).atomic.func1(0x18ef1c0, 0xc0412a5920, 0xc040de5d80, 0x0, 0x0)
> 	/home/travis/gopath/src/github.com/algorand/go-algorand/util/db/dbutil.go:226 +0x97
> github.com/algorand/go-algorand/util/db.(*Accessor).atomic(0xc0444fad28, 0xc0412810e0, 0x18e5f80, 0xc0444fae78, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/home/travis/gopath/src/github.com/algorand/go-algorand/util/db/dbutil.go:311 +0xa9c
> github.com/algorand/go-algorand/util/db.(*Accessor).AtomicCommitWriteLock(...)
> 	/home/travis/gopath/src/github.com/algorand/go-algorand/util/db/dbutil.go:369
> github.com/algorand/go-algorand/ledger.(*accountUpdates).commitRound(0xc0444faad0, 0x1, 0x560, 0x140)
> 	/home/travis/gopath/src/github.com/algorand/go-algorand/ledger/acctupdates.go:1190 +0xbff
> github.com/algorand/go-algorand/ledger.(*accountUpdates).commitSyncer(0xc0444faad0, 0xc0443eed80)
> 	/home/travis/gopath/src/github.com/algorand/go-algorand/ledger/acctupdates.go:1100 +0x62
> created by github.com/algorand/go-algorand/ledger.(*accountUpdates).initializeFromDisk
> 	/home/travis/gopath/src/github.com/algorand/go-algorand/ledger/acctupdates.go:758 +0xc64
> Other goroutines holding locks:
> goroutine 1429269 lock a7
> ledger.go:359 ledger.(*Ledger).Lookup { l.trackerMu.RLock() } <<<<<
> eval.go:250 ledger.startEvaluator { incentivePoolData, err := l.Lookup(eval.prevHeader.Round, poolAddr) }
> eval.go:820 ledger.(*Ledger).eval { eval, err := startEvaluator(l, blk.BlockHeader, len(blk.Payset), validate, false) }
> ledger.go:454 ledger.(*Ledger).AddBlock { updates, err := l.eval(context.Background(), blk, false, nil, nil) }
> ledger_test.go:882 ledger.TestLedgerBlockHdrCaching { err := l.AddBlock(blk, agreement.Certificate{}) }
> ```

Yes, I'm already on that.

**Comment by tsachiherman** [comment]
> I agree on 1 and 3 but 2 with testing all fields for expected values looks as overkill. `dump` is an as-is thin dumper of `BalanceRecord` data structure. In the same guess checking for `AppParams` makes sense since access to `AppParams` was one of reason of creation this command. Thank you for the feedback.

We need to test all the fields that we're committing to support in the future. That's our "ticket" for saying "hey, we will give you the following pieces of information if you'll do that". The fact that the underlying data structure happens to align with that is a mere incident.

**Comment by algorandskiy** [comment]
ok, `account dump` commits on a balance record with application parameters in a canonical format to be re-used by other tools (tealdbg). From this point of view a simple (de)serialization check with `msgpacktool` should be enough.

**Comment by tsachiherman** [comment]
> ok, `account dump` commits on a balance record with application parameters in a canonical format to be re-used by other tools (tealdbg). From this point of view a simple (de)serialization check with `msgpacktool` should be enough.

I don't know if it's possible, but if you can get into a consistent account data, you could just compare the msg packed file with a golden image. The goal is to ensure we don't make any undesired changes. It's ok if it would force us to revisit the test once changes are done.

**Comment by algorandskiy** [comment]
@tsachiherman added comparison against the pre-recorded objects. The only problem the test takes 30s instead of 5.

**Comment by tsachiherman** [comment]
> @tsachiherman added comparison against the pre-recorded objects. The only problem the test takes 30s instead of 5.

I think that 30s isn't an issue once it works.

**Pull request merged**
