### PR TITLE
config: update vFuture consensus and configuration for 5MB blocks

### PR DESCRIPTION
**Pull request by cce**
## Summary

This updates the vFuture consensus parameters for 5MB blocks, 3.5s filter timeout, and updates configuration defaults for the next release to use a larger assembly timeout and TX pool size.

## Test Plan

Existing tests should pass.

### CODE REVIEW

**Review by brianolson — COMMENTED** [review]
good except maybe localTemplate.go needs a version[24] ?

**Comment by brianolson** [comment]
maybe add network/wsPeer.go `maxMessageLength` to this?

**Comment by brianolson** [comment]
for comparison, this is what I've been running lately
https://github.com/algorand/go-algorand/pull/4262

**Comment by cce** [comment]
@brianolson config v23 was just introduced in the 320-rounds branch so I think it is OK to tack these new defaults on to it.

**Review by algorandskiy — APPROVED** [review]

**Pull request merged**
