### PR TITLE
Increase pending proposals queue

### PR DESCRIPTION
**Pull request by tsachiherman**
## Summary

The number of proposals generated derives from the consensus params. At this time, we have (up to) 20 proposals.
In a rare network event, when all the relays connected to a given proposer are lagging behind, the winning proposal could be dropped out, causing a 21 second round.

This was verified by lowering the proposalBufferSize dramatically, confirming that the only dropped agreement messages were proposals, and that a 21 second rounds were introduced.

## Test Plan

Tested by lowering the proposalBufferSize to 2, and running a deployed network. Once every few *hours*, we would have a 21-second round.

### CODE REVIEW

**Comment by onetechnical** [comment]
Thanks for testing this! I'm psyched you could recreate it!

**Review by egieseke — APPROVED** [review]
Looks good.  Are there logs for the dequeued messages?

**Comment by tsachiherman** [comment]
> Looks good. Are there logs for the dequeued messages?

No. For performance & security reasons, there aren't any logs for an individual dropped message. ( since we don't want an attacker to force us writing to disk.. )

**Review by onetechnical — APPROVED** [review]

**Comment by pbennett** [comment]
You should probably at least track metrics for it so it could be tracked w/ prometheus or other telemetry options.

**Comment by tsachiherman** [comment]
> You should probably at least track metrics for it so it could be tracked w/ prometheus or other telemetry options.

Yes, that's how I confirmed that this change was contributed to this issue. What I wasn't able to confirm was that there aren't other causes for this issue.

**Pull request merged**
