### PR TITLE
Tools: add support for developing in OpenSUSE Tumbleweed

### PR DESCRIPTION
**Pull request by lamg**
## Summary

Support for building source in OpenSUSE Tumbleweed

## Test Plan

Built with my local machine.

### CODE REVIEW

**Review by onetechnical — APPROVED** [review]
The change here looks straightforward, so I'm okay with it, but I haven't tested it directly.

**Comment by onetechnical** [comment]
Pulled back approval because there are some missing build dependencies here - perhaps glibc and gcc? Need to experiment a bit more.

**Comment by lamg** [comment]
Just checked following the README instructions with `docker run -it opensuse/tumbleweed bash` and now the build works. However I had to manually do `zypper install git go awk`

**Comment by onetechnical** [comment]
Re-verified in docker. Thanks!

**Review by gmalouf — APPROVED** [review]

**Comment by gmalouf** [comment]
Thank you!

**Pull request merged**
