### PR TITLE
Teal3 review

### PR DESCRIPTION
**Pull request by jannotti**
These are changes suggested on the TEAL3 code review.  They simplify and cleanup a few things, but should be very safe.  Mostly just changes in structure of assembler.

### CODE REVIEW

**Review by brianolson — COMMENTED** [review]
LGTM. Is this ready for an Approve? I like a lot of these refactors. They clean up some design decisions that don't fit anymore.

**Comment by jannotti** [comment]
Yes, it's ready to go.  Not absolutely everything got in, but time to get to work on v4, and maybe I can get some of them in there.

**Review by algorandskiy — COMMENTED** [review]
I think it looks good, please fix the build

**Comment by jannotti** [comment]
Fixed, using a special technique I have developed at Algorand.  I asked it to try again.

Are there any straightforward ways to improve our CI?  I tried to be a good little software engineer this week and make three small PRs even though it was all fairly related functionality.  This meant I was trying to keep track of three different builds, each of which takes hours, and each fails intermittently for random reasons.  Out of 5-6 failed builds, one real bug was caught, and that was a lint failure, buried under many thousands of lines of output.  This can't be good for productivity.

And now I also have a conflict to deal with in another PR because someone got lucky and didn't have the build fail when they made a change, so theirs beat mine in.

**Review by brianolson — APPROVED** [review]

**Pull request merged**
