### PR TITLE
Fix intermittent  failure of algohTimeoutTest.exp 

### PR DESCRIPTION
**Pull request by egieseke**
## Summary

Fix error running algohTimeoutTest.exp by providing sufficient time for the network to start.

## Test Plan

Ran make integration and testing on Travis with PR.

### CODE REVIEW

**Comment by egieseke** [comment]
I am fairly confident that the cause of the intermittent test failure was due to a short 5-second timeout for the network startup.  I reset that to 60 seconds.  The test should be more reliable now.

**Comment by algorandskiy** [comment]
I have a similar PR #1636 and @tsachiherman did not let it in until we understand why it takes a long for nodes to start. I guess I have a similar issue now after running exclusive app pingpongs - network startup takes significantly longer after even a single 180 sec test run.

**Comment by egieseke** [comment]
> I have a similar PR #1636 and @tsachiherman did not let it in until we understand why it takes a long for nodes to start. I guess I have a similar issue now after running exclusive app pingpongs - network startup takes significantly longer after even a single 180 sec test run.

This test is adversely affecting the productivity of the dev team by causing builds to fail and delaying PRs.  We should commit either your fix or mine and create a separate ticket to look into the problem of slow startup.

**Comment by tsachiherman** [comment]
Do you see this test failing on all platforms, or only a specific one ?
If it's a platform specific, than isolating the slow activity and extending it's timeout for that particular platform makes sense.
In general, i'm opposing to increasing test timeout since I'd like to see consistant product improvement rather than consistant tech debt that eventually get deleted by Ian.

**Comment by tsachiherman** [comment]
Just to be clear, if you'd like to tackle this properly in the coming sprint, than yes, by all means - "unblock" the master and take the work by creating a ticket.

**Review by tsachiherman — APPROVED** [review]
I think that we'll need to figure out why this platform is so slow and fix it. But it's ok to do this another day!

**Pull request merged**
