### PR TITLE
fix TestDBConcurrencyRW

### PR DESCRIPTION
**Pull request by algobolson**
## Summary

Use a channel instead of an atomic busy-wait to sync test thread starts.
Clean up sqlite db files. (repeated testing eventually failed due to out-of-disk error)

## Test Plan

Ran the test repeatedly for a while, it used to hit the intermittent crash after a few minutes but now I haven't seen a crash in much longer.
`while go test -count=50 github.com/algorand/go-algorand/util/db; do date; done`

### CODE REVIEW

**Comment by zeldovich** [comment]
The cleanup thing is definitely a good idea -- thanks!

Do you have an example output for this test failing or crashing?  I can't seem to reproduce it on my laptop.

**Comment by algobolson** [comment]
It might only reproduce on underpowered Linux hosts (2 cores or fewer) like what we were using for our test host and a small VM I reproduced this on. I think the test design would rely on multiple cores or for the Go runtime to preempt threads and I guess sometimes the Go runtime wasn't good enough at preempting the busy-wait threads.

**Comment by zeldovich** [comment]
Ah, makes sense.

Can you just check that the test still catches the intended bug?  The test should fail if the following change is applied:

    --- a/util/db/dbutil.go
    +++ b/util/db/dbutil.go
    @@ -227,6 +227,8 @@ func URI(filename string, readOnly bool, memory bool) string {
            }
            if memory {
                    uri += "&mode=memory"
    +       }
    +       if readOnly || memory {
                    uri += "&cache=shared"
            }
            return uri

**Comment by algobolson** [comment]
yup. that promptly fails.

**Pull request merged**
