### PR TITLE
Simulate: Pack transaction reference arrays for unnamed resources

### PR DESCRIPTION
**Pull request by jasonpaulos**
## Summary

See #5616 for issue description

## Test Plan

todo

### CODE REVIEW

**Comment by SilentRhetoric** [comment]
Hi Jason, is this still planned?

**Comment by joe-p** [comment]
@SilentRhetoric I'm starting to work on it this week. Initial plan is to come up with a very simple function in JS for AVM <9 app calls. Then iterate on top of that to support AVM9 resource sharing. Then once a good algorithim is reached it can be put into `algod`. There are some edge cases like inner call to AVM<9 from AVM9+ and I'm not sure how nuanced the simulate response is, so don't know the exact scope of work here but I think it's manageable and hopefully ready by EOY.

**Comment by joe-p** [comment]
Turns out that the simulate response was much more detailed than I anticipated, which made development much easier. 

Working TypeScript implementation with tests for all functionality for both AVM8 and AVM9 is here: https://github.com/joe-p/resource-packer/tree/main

Next step is to do some more testing of the edge cases and then implementation into `go-algorand` can be started. I think returning `{boxes, apps, accounts, assets}` for each transaction as part of the response makes the most sense (opposed to returning the entire txn object) but open to other ideas.

**Comment by jasonpaulos** [comment]
Closing as this is very outdated and @joe-p has started a new effort in #6015

**Pull request closed without merging**
