### PR TITLE
DevOps: Extend Alphanet topology

### PR DESCRIPTION
**Pull request by egieseke**
## Summary

Updated Alphanet topology so that each node is hosted separately.

## Test Plan

Used the alphanet-extension recipe to create new hosts, and updated their genesis files to reference alphanet.  Migrated key and partkey files to new nodes.  Decommissioned old nodes collocated with the Relays.  Validated that the network still functions.

### CODE REVIEW

**Comment by onetechnical** [comment]
If this is long-running, should this be targeted at 'master' instead of 'feature/alphanet'? Maybe we never "back merge" to master.

**Review by onetechnical — APPROVED** [review]
Hmm, there's a code/maintenance smell here, but I'm not quite sure how we want to refactor it yet. We're also missing some steps for configuration of these new nodes.

I think this is okay for our implementation here, but we're getting increasingly difficult to manage the network, now that we're split across two different builds. (Plus I think we need some work to re-integrate monitoring/telemetry for alpha net appropriately?)

**Review by algojack — APPROVED** [review]

**Comment by egieseke** [comment]
> 

@onetechnical Seems that it should be applied to master when feature/alphanet is merged into master.

**Comment by egieseke** [comment]
> Hmm, there's a code/maintenance smell here, but I'm not quite sure how we want to refactor it yet. We're also missing some steps for configuration of these new nodes.
> 
> I think this is okay for our implementation here, but we're getting increasingly difficult to manage the network, now that we're split across two different builds. (Plus I think we need some work to re-integrate monitoring/telemetry for alpha net appropriately?)

We discussed this as a group and decided to use the extension method as we did for betanet.  The network metrics are functioning and are visible in the network performance monitor: https://app.datadoghq.com/dashboard/wsv-nut-ne2/network-performance-monitor?from_ts=1658772763050&to_ts=1659377563050&live=true

**Comment by egieseke** [comment]
Added setup instructions here: https://algorand.atlassian.net/wiki/spaces/DEVOPS/pages/2463596545/Alphanet+Setup+Notes

**Pull request merged**
