### PR TITLE
Onetechnical/restable2.1.2

### PR DESCRIPTION
**Pull request by onetechnical**
## Highlights

Bug fixes and enhancements. Note that there is a one time long startup time to re-encode the accounts database, which will take a few minutes to complete.

## Changes

1. General
    * Bug Fixes
        * update the suggested fee mechanism to meet the current transaction pool fee structure (#1376)
        * eliminate nil map entries on Merkle trie cache
1. Config
    * New Feature - add optional startup vacuuming for the balances database
1. Ledger
    * Enhancements
        * improve client-side catchpoint catchup performance
        * add vacuumming to the database upgrade process
    * Bug Fixes
        * listCreatablesStmt is selecting 3 columns instead of 2
        * avoid using encodedAccountsRange and replace with a single query
        * extend ledger request timeout
        * avoid redundant info message for replacing block 0
1. Tools
    * Enhancement - fetch balance from indexer for tealdbg
1. Tests
    * Enhancements
        * e2e test: create+delete create+clear in 1 tx
        * add some minimal documentation for the test directory
        * REST API test script for /v2/applications
        * added TestListCreatables to test ListAssets and ListApplications
    * Bug Fix - fix failing rekey test by keeping account total < 1 algo
1. Other
    * Enhancements
        * update mule package deploy to use new agents syntax
        * remove go version from Travis file (#1253)
    * Bug Fix - fix Makefile to work with Ubuntu 20.04

## Protocol Upgrade
This release does not contain a consensus protocol upgrade.

## Other Notes
A database migration is included this release, which will add a one-time startup delay of around three minutes. This is for re-encoding of the accounts database, if needed. Note: the database schema will remain compatible with the previous release. Please plan your upgrade accordingly.

## Additional Resources
* [Algorand Forum](https://forum.algorand.org)
* [Developer Documentation](https://developer.algorand.org)

## Test Plan

Standard release testing. ARM64 Integration Tests are allowed to fail, due to a performance issue. These have been manually tested.

### CODE REVIEW

**Comment by tsachiherman** [comment]
let's wait until after the betanet deployment before merging this one ?

**Comment by onetechnical** [comment]
Of course! Want to get testing started. We can always kill it if there are new fixes.

**Comment by tsachiherman** [comment]
Are you planning to merge this one followed by another one, or just a 2.1.3 ?

**Comment by onetechnical** [comment]
Closing this in favor of a new merge.

**Pull request closed without merging**
